name: Nathan Reynolds
description: "Django freelancer, Norwich UK"

markdown: redcarpet
highlighter: 'pygments'
logo: false
paginate: 15

# RSS feed
url: 'http://nreynolds.co.uk'
author: 'Nathan Reynolds'
